# .github/workflows/input-example.yaml
name: Input example

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: World

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.name }}"
